### ISSUE TITLE
No longer working with recent updates

### ISSUE THREAD

**Issue by NICHOLAS85** [maxiberta/kwin-system76-scheduler-integration#1]
Hello! I've been using this project for awhile and it seems that somethings broken in recent updates. I am getting the following error in my logs when switching windows and I see nice levels are not being automatically adjusted like they used to,

```
file:///home/nicholas/.local/share/kwin/scripts/kwin-system76-scheduler-integration/contents/code/main.js:2: TypeError: Cannot read property 'pid' of null
```

Just curious if there is a simple fix but I do see its been awhile since this repo has received updates.

Thanks!

**Comment by maxiberta** [comment]
Hi! Thanks for reporting this issue. Are you running Kwin 6.0? If so, that's great! Mind trying this simple fix? https://github.com/maxiberta/kwin-system76-scheduler-integration/commit/093a269670275feaa240d02c712f1ec8b812fd80
Cheers

**Comment by NICHOLAS85** [comment]
Thanks for the prompt reply! I'm running Fedora release 39 which is not using Kwin 6.0 yet, I'm running 5.27.11. I tried your fix anyways and get the following error:
```js
main.js:1: error: Cannot call method 'connect' of undefined**
```

**Comment by NICHOLAS85** [comment]
Works like normal upon updating to Fedora 40 using KWin 6.0 and reinstalling the plugin from git.
