### ISSUE TITLE
TypeError: Cannot read property 'pid' of null

### ISSUE THREAD

**Issue by riccardv** [maxiberta/kwin-system76-scheduler-integration#2]
Every time an application has been launched by desktop there is a script error on syslog:

Mar 22 12:20:42 5cd2512wtv kwin_wayland[4301]: file:///home/user/.local/share/kwin/scripts/kwin-system76-scheduler-integration/contents/code/main.js:5: TypeError: Cannot read property 'pid' of null

KDE Plasma 6.0.2

**Comment by maxiberta** [comment]
Thanks for your report! This looks like issue https://github.com/maxiberta/kwin-system76-scheduler-integration/issues/1 - but that's with 5.27.11. For KDE 6, this simple patch appears to work for me. Would you mind trying it? https://github.com/maxiberta/kwin-system76-scheduler-integration/commit/093a269670275feaa240d02c712f1ec8b812fd80. It can be applied on ~/.local/share/kwin/scripts/kwin-system76-scheduler-integration/contents/code/main.js, then restart it at System Settings -> KWin Scripts . Thanks!

**Comment by riccardv** [comment]
I'm already using the "windowActivated" function

**Comment by riccardv** [comment]
Hi @maxiberta , 
enabling the debug console I can see the getting of pid successfully. Probably there are many conditions when the script fail. A check on pid != null should be done :)

Thank you for your work.
